version: '2'
services:
  worker:
    image: maven:3.8.4-openjdk-17-slim
    volumes:
      - .:/apps
    working_dir: /apps
    ports:
      - "8080:8080"
      - "8000:8000"
    # Substitute the following with whatever
    # makes sense for your java webapp
    command: mvn clean package jetty:run
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8000