version: '2'
services:
  worker:
    image: maven:3.5.0-jdk-8
    volumes:
      - .:/apps
    working_dir: /apps
    ports:
      - "8080:8080"
    # Substitute the following with whatever
    # makes sense for your java webapp
    command: mvn clean package jetty:run