package com.sdc.parser.Resource;

import org.hl7.fhir.r4.model.PractitionerRole;

import ca.uhn.fhir.context.FhirContext;

public class PractitionerRoleHelper {

	public static PractitionerRole createPractitionerRolePractitioner(FhirContext ctx) {
		PractitionerRole practRole = new PractitionerRole();
        practRole.getMeta().addProfile("http://hl7.org/fhir/us/cancer-reporting/StructureDefinition/us-pathology-related-practitioner-role");
        practRole.getText().setStatus(org.hl7.fhir.r4.model.Narrative.NarrativeStatus.GENERATED);
        practRole.getText().setDivAsString("<div xmlns=\"http://www.w3.org/1999/xhtml\"><div class=\"hapiHeaderText\">fake Observation</div><table class=\"hapiPropertyTable\"><tbody><tr><td>Identifier</td><td>6547</td></tr></tbody></table></div>");
        practRole.addIdentifier().setSystem("http://someIdentifier.com").setValue("pathpract1");
        practRole.addIdentifier().setSystem("http://hl7.org/fhir/sid/us-npi").setValue("193757595");
        practRole.addCode().addCoding().setSystem("http://hl7.org/fhir/us/cancer-reporting/ValueSet/us-pathology-provider-types").setDisplay("Pathologist principally interpreting results on pathology testing").setCode("principal-result-interpreter");
        //TODO: add reference Practitioner as config/autogenerated link 
        //String encoded = ctx.newXmlParser().setPrettyPrint(true).encodeResourceToString(pract);
		return practRole;
	}
}
