package com.sdc.parser.Resource;

import org.hl7.fhir.r4.model.PractitionerRole;

import ca.uhn.fhir.context.FhirContext;

public class PractitionerRoleHelper {

	public static PractitionerRole createPractitionerRolePractitioner(FhirContext ctx) {
		PractitionerRole practRole = new PractitionerRole();
        practRole.getMeta().addProfile("hhttp://hl7.org/fhir/us/cancer-reporting/StructureDefinition/us-pathology-related-practitioner-role");
		practRole.addIdentifier().setSystem("http://someIdentifier.com").setValue("pathpract1");
        practRole.addIdentifier().setSystem("http://hl7.org/fhir/sid/us-npi").setValue("193757595");
        practRole.addCode().addCoding().setSystem("http://hl7.org/fhir/us/cancer-reporting/ValueSet/us-pathology-provider-types").setDisplay("Pathologist principally interpreting results on pathology testing").setCode("principal-result-interpreter");
        //TODO: add reference Practitioner as config/autogenerated link 
        //String encoded = ctx.newXmlParser().setPrettyPrint(true).encodeResourceToString(pract);
		return practRole;
	}
}
